### ISSUE TITLE
About load ckpt

### ISSUE THREAD

**Issue by QiopeWallt** [lxa9867/ControlVAR#12]
The epoch folder we saved from your train_control_var.py is shown in the figure. Do the model_1 model_2 model here refer to cond_model var respectively?
In addition, we noticed that the cond_model in your train_control_var.py did not load the ckpt code. Is this something I didn't notice or did you omit it?
![image](https://github.com/user-attachments/assets/6a5f3a68-5c43-429b-8d70-b742f6d21a72)

**Comment by lxa9867** [comment]
I think ControlVAR doesn't require a pretrained cond model as it is class conditioned.

The cond_model API is for text-conditioned model which is not released in this repo. Please ignore the cond model as they just output class labels.

**Comment by QiopeWallt** [comment]
So what dose model1/2 refer to?
Or I just load model

**Comment by lxa9867** [comment]
I think the .pth file should be directly loaded.
