### ISSUE TITLE
about inference 

### ISSUE THREAD

**Issue by pokameng** [lxa9867/ControlVAR#14]
`python train_control_var_hpu.py \
--batch_size $bs \
--dataset_name imagenetC \
--data_dir $path_to_ImageNetC \
--gpus $gpus \
--output_dir $output_dir \
--multi_cond True \
--val_only True \
--resume $ckpt_path`
hello! thanks for your great works
when i run as above code,sth is wrong:

ImportError: /lib64/libldap.so.2: undefined symbol: EVP_md2, version OPENSSL_3.0.0

and  I can only run on GPU not HPU

@lxa9867

**Comment by lxa9867** [comment]
I think this issue has been solved. Closing.
