### ISSUE TITLE
About entity mask color mapping in Figure 3 of the paper

### ISSUE THREAD

**Issue by strive789** [lxa9867/ControlVAR#16]
In your paper, it is mentioned that (0,0,0) is used as the background. Why is the background not mapped as (0,0,0) in Figure 3, but instead represented by other colors?
![922e7bd29e4a625ab807e973c96893d](https://github.com/user-attachments/assets/9d5ea782-1e8c-4517-a3e8-adbeaaf4c299)

**Comment by lxa9867** [comment]
Hi,

Thanks for the interest. 0,0,0 is used for background which means no mask region with the pseudo-labeled dataset. In the class agnostic segmentation presented in Fig 3, the blue area indicates sky instead of undefined region.

**Comment by strive789** [comment]
Thank you for your response. I understand your point now. In Fig 3(b), gray and black represent the foreground segmentation masks, while white represents the irrelevant parts.

Your work is excellent! It has provided me with a lot of inspiration.

**Comment by lxa9867** [comment]
I am happy you find this work helpful :)
