### ISSUE TITLE
Controlling conditional loading issues

### ISSUE THREAD

**Issue by PXinTao** [lxa9867/ControlVAR#17]
First of all, thank you for sharing your code and work. I have been going through it, and I have a question regarding how multi-condition inputs, such as Canny edge maps and depth maps, are handled and passed into the model.

How are the condition images (such as Canny edge maps and depth maps) loaded and processed in the code?
How are these conditions passed into the model alongside the main images? Is there a specific part of the code that handles the fusion of these condition images?
I would greatly appreciate your help with clarifying this.

Thank you once again!

**Comment by lxa9867** [comment]
Hi,

Thanks for your interest.

We process the conditions in the dataset (for efficiency consideration) [code](https://github.com/lxa9867/ControlVAR/blob/main/datasets/imagenetC.py#L129). 

```
cond_type = random.choices(['mask', 'canny', 'normal', 'depth'], [0.25, 0.25, 0.25, 0.25], k=1)[0]

sample = {'image': image, 'mask': cond, 'cls': cls, 'ignore_mask': ignore_masks, 'ignore_mask_': ignore_masks_,
                  'type': torch.tensor(self.cond_idx[cond_type])}
```

We evenly sample reach control types and output images and controls from the dataset.

**Comment by PXinTao** [comment]
Thank you so much for your detailed response and clarification!  Your answer has significantly helped me better understand your implementation.

**Comment by lxa9867** [comment]
I am happy that helps. Closing the issue.
