### ISSUE TITLE
Great work. Have you tried multiple control parse at the same time? 

### ISSUE THREAD

**Issue by dingkwang** [lxa9867/ControlVAR#2]
For example, if I want to use mask control plus depth control. What is the best way to achieve it?

**Comment by lxa9867** [comment]
We didn't try multiple controls. But it should be able to achieve by using cfg in a form like, 0.5 * (x_mask + x_depth) - x_none.

This was used in a cvpr paper for diffusion-based controllable image generation. I don't remember the paper name though.

**Comment by dingkwang** [comment]
Good point, but I didn't provide a good example. My control condition are more complicate than just mask and depth (but they are still image pixels with the same size). Do you think I can modify the mask_type to allow for more than one control? 

`                elif args.mask_type == 'interleave_append':
                    # Image: r1, r2, r3, Mask: m1, m2, m3
                    # New: (m1, r1), (m2, r2), (m3, r3)
`
to 

`                elif args.mask_type == 'interleave_append':
                    # Image: r1, r2, r3, MaskA: ma1, ma2, ma3 MaskB: mb1, mb2, mb3
                    # New: (ma1, mb1, r1, ), (ma2, mb2, r2), (ma3, mb3, r3)
`

**Comment by lxa9867** [comment]
I think this is feasible but it will make the sequence length longer and require more model capacity.
