### ISSUE TITLE
Inference failure

### ISSUE THREAD

**Issue by bigshuimu** [lxa9867/ControlVAR#21]
Hello, your work looks great. I tried to use the pretrained model you provided to generate images, but something went wrong and the images look terrible. How can I load the model correctly?
![image](https://github.com/user-attachments/assets/8eb40eb6-823e-4cc4-9516-03065b6dfb01)
In addition, I ran train_control_var.py with the following parameters.
```python
    args.batch_size = 8
    args.dataset_name = 'imagenetC'
    args.data_dir = '/opt/data/private/qy/ControlVAR/ImageNet2012'
    args.gpus = 1
    args.output_dir = './output'
    args.multi_cond = True
    args.val_only = True
    args.resume = './pretrained/d30.pth'
    # args.resume = False
    args.lr_scheduler = 'linear'
    args.var_pretrained_path='./pretrained/var_d30.pth'
```

**Comment by lxa9867** [comment]
Hi,

Thanks for your interest. It seems like the model is not loaded. Can you post your cmd here? Thanks.

**Comment by bigshuimu** [comment]
python3 train_control_var.py --batch_size 8 --dataset_name imagenetC --data_dir ImageNet2012 --gpus 1 --output_dir output --multi_cond True --val_only True --resume pretrained/d30.pth

**Comment by bigshuimu** [comment]
I attempted to add some missing functions and code such as `resume`, to `train_control_var.py`, which resolved the model loading issue. 😎Thanks again to the author for their work.❤️
![media_images_images_100_c3f48d71af4014bc4cf3](https://github.com/user-attachments/assets/fe8a7d38-7b41-4170-bd47-102bf60aa4d2)

**Comment by zhanghh-031102** [comment]
I also encountered the same problem about weights. How did you solve it?
