### ISSUE TITLE
Inpainting

### ISSUE THREAD

**Issue by Ferenas** [lxa9867/ControlVAR#3]
Hi, thanks for sharing this work! I am interested about how to to process Inpainting for VAR/Control VAR. Are the masked image regions set to 0, and fed to VAR for inference directly?

**Comment by lxa9867** [comment]
Thanks for your interest. We teacher-force some regions in the image and predict the remaining to achieve the inpainting.

**Comment by Ferenas** [comment]
hi, thanks for ur reply! However, I still got confused about this. VAR will generate the output tokens, e.g., 680 tokens, with inputing and scaling the whole image tokenized features, and perform next-scale-token prediction. So how to specifically teacher-force some regions? Theoretically, all image region should serve as the input to generate the corresponding scale-level tokens, thereafter performing reconstruction.

**Comment by lxa9867** [comment]
In our implementation, we start from a 256x256 size binary mask and then resize it (nearest) to low resolution to teacher-force the unmasked regions.

I believe VAR uses the same way to conduct the inpainting.

**Comment by Ferenas** [comment]
Thanks for ur reply! I have tried to implement what you said, and the code line shall look like:
>
<img width="1332" alt="截屏2024-08-27 15 00 59" src="https://github.com/user-attachments/assets/e42e05e3-60f0-49ff-8ad4-15b95ae256da">



Here I interpolate the an extra binary mask as the scale increases, and directly erasing the corresponding f_hat in `idxBl_to_var_input` function, is this implementation correct?

**Comment by zijinY** [comment]
@Ferenas I have same issue for inpaint. Have you tried this ?

**Comment by egbertYeah** [comment]
@Ferenas the performace?
