### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by QiopeWallt** [lxa9867/ControlVAR#6]
which python and cuda version did your team choose?
I choose 3.10 but something seems wrong :"can import .PCA"

**Comment by lxa9867** [comment]
We use python 3.10 and cuda 12.3 during the experiment. Which file gives you the error?

**Comment by QiopeWallt** [comment]
I have fixed this question,but I encountered “No module named 'models.vpa'”  when i try to train. Vpa file did not exist in the group "model".
![image](https://github.com/user-attachments/assets/1e07e889-d760-48b9-8813-eedcc8949820)

**Comment by lxa9867** [comment]
I updated the init file recently. Please delete that import from init.

**Comment by QiopeWallt** [comment]
OK, I've used your updated file(btw ty),but where is the difination of MaskVAR?
![image](https://github.com/user-attachments/assets/cf371a3a-7181-43f0-99cd-3149959741de)

**Comment by dingkwang** [comment]
> OK, I've used your updated file(btw ty),but where is the difination of MaskVAR? ![image](https://private-user-images.githubusercontent.com/144539759/367624012-cf371a3a-7181-43f0-99cd-3149959741de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0Mzg5ODcsIm5iZiI6MTcyNjQzODY4NywicGF0aCI6Ii8xNDQ1Mzk3NTkvMzY3NjI0MDEyLWNmMzcxYTNhLTcxODEtNDNmMC05OWNkLTMxNDk5NTk3NDFkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQyMjE4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGQ2MDhmNzc4YjRkNDg2NDA4OTRmNzM5NzQ3YmJkNzc0NzI4NjAwNWFiYzQyZjk1ZTI5Mzg1MjQwYzY5N2E1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8R91OTUUg0RB-Xv2S3KycmS91GRv6bdmb-pDwwzIDB8)

Just replace it with ControlVAR. It seems to be a typo.
