### ISSUE TITLE
Dataset issue

### ISSUE THREAD

**Issue by OrangeCat7777777** [lxa9867/ControlVAR#7]
I have downloaded the dataset from huggingface. As mentioned in README, I should arrange the dataset as 
```
ImageNet2012
├── train
├── val
├── train_canny
├── train_mask
├── train_normal
├── train_depth
├── val_canny
├── val_mask
├── val_normal
└── val_depth
```
However, I can only find a bunch of parquet files from the downloaded ImageNet-C (and all of them seem to be in the train split). What should I do with it?

**Comment by lxa9867** [comment]
Thanks for your interest. Let me download and check. Will get back to you soon.

**Comment by qiuk2** [comment]
Hi,
We re-upload our dataset again at https://huggingface.co/datasets/qiuk6/ImageNet2012_condition, it may take 2-3 days to upload all the files! Feel free to ask if you have any more problems.
